zh-CN:
  githug:
    cli:
      tasks:
        play: 初始化游戏
        test: 根据文件路径测试关卡 
        hint: 查看本关线索
        reset: 重玩本关

      reset:
        resetting: 重置本关中
        does_not_exist: 关卡不存在

      make_directory:
        change_dir: 请切换到git_hug目录
        no_dir_found: 没有githug目录，你想要创建一个吗？
        exiting: 正在退出

    game:
      play_level:
        welcome: 欢迎来到Githug！
        success: 恭喜大侠过关！
        failure: 革命尚未成功，大侠仍需努力！
        hint_prompt: 大侠别忘了可以用`githug hint`查看锦囊，用`githug reset`重玩本关。

      test_level:
        valid: 成功！
        invalid: 失败！

    level:
      level: "关卡："
      difficulty: "难度："
      no_hints: 本关暂无提示

  level:
    init:
      description: 一个新目录`git_hug`已被创建，请将它初始化为Git仓库。
      hints: 
        - "你可以在shell中执行`git`命令来查看可用的git命令列表。"
    config:
      description: 设置你的git名称和email，这对你的commit是否可识别很重要。
      hints:
        - 这些设置需要在config中进行设置，如果大侠你实在不知道怎么办的话，不妨运行一下：`git help config`。
      questions:
        - 你行走江湖的名号是？
        - 你的邮件地址是？
      messages:
        - "你配置的名号是："
        - "你配置的邮件地址是："
    add:
      description: 当前目录下有一个名为`README`的文件，请将它加入到staging区域。注意：每一关开始都会创建新的仓库，所以不要试图去找上一关的文件。
      hints:
        - 你可以在shell中执行`git`命令来查看可用的git命令列表。
    commit:
      description: 文件`README`已经被添加到了staging区域，请提交它。
      hints:
        - 提交时必须包含注释。
    clone:
      description: 请clone仓库：https://github.com/Gazler/cloneme
      hints:
        - 你应该看一下：https://github.com/Gazler/cloneme
    clone_to_folder:
      description: 请clone仓库：https://github.com/Gazler/cloneme 到`my_cloned_repo`
      hints:
        - 本关和上一关类似，`git clone`有一个可选参数。
    ignore:
      description: vim编辑器会为所有当前打开的文件生成`.swp`（swap文件）后缀的文件。我们不希望它们出现在仓库中。本关的任务是让git仓库忽略`.swp`文件。
      hints:
        - 你可能注意到了仓库中有一个名为`.gitignore`的文件。
    include:
      description: 注意那些后缀为'.a'的文件，我希望git忽略除'lib.a'之外的其它文件。
      hints:
        - 用`git gitignore --help`，读一下关于将模式取反的可选前缀的部分。
    status:
      description: 仓库中有一些文件，其中一个没有被git跟踪，它是哪一个呢？
      hints:
        - 你要找到一个命令来查看仓库的状态。
      questions:
        - 那个未被跟踪的文件名称是？
